version: "3"
services:
# app doesn't matter sometimes it's called web but it's a matter of preference
  app:
    container_name: docker-node-mongo
    # If it fails it'll restart
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
